CREATE TABLE IF NOT EXISTS users
(
    id        TEXT PRIMARY KEY UNIQUE,
    email     TEXT NOT NULL UNIQUE,
    pass_hash BLOB NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_email ON users (email);

CREATE TABLE IF NOT EXISTS apps
(
    id     TEXT PRIMARY KEY UNIQUE,
    name   TEXT NOT NULL UNIQUE,
    secret TEXT NOT NULL UNIQUE
);
